version: '3.8'
name: 01_web_mimo_certity
services:
  database.localhost:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./certify_init.sql:/docker-entrypoint-initdb.d/certify_init.sql
    networks:
      - network
    ports:
      - "5433:5432"

  certify.localhost:
    image: mosipid/inji-certify:0.10.2
    user: root
    ports:
      - 8090:8090
    environment:
      - container_user=mosip
      - active_profile_env=default, csvdp-farmer
      - SPRING_CONFIG_NAME=certify
      - SPRING_CONFIG_LOCATION=/home/mosip/config/
      - enable_certify_artifactory=false
      - download_hsm_client=false
      - mosipbox_public_url=http://certify.localhost:8090
    volumes:
      - ./config/certify-default.properties:/home/mosip/config/certify-default.properties
      - ./config/certify-csvdp-farmer.properties:/home/mosip/config/certify-csvdp-farmer.properties
      - ./config/certify-mock-mdl.properties:/home/mosip/config/certify-mock-mdl.properties
      - ./data/CERTIFY_PKCS12:/home/mosip/CERTIFY_PKCS12
      # This can be disabled if one uses plugins included in inji-certify-with-plugins docker image.
      - ./loader_path/certify/:/home/mosip/additional_jars/
      # modify the below file to change the identity fields in the VC
      - ./config/farmer_identity_data.csv:/home/mosip/config/farmer_identity_data.csv
    networks:
      - network
    depends_on:
      - database.localhost

  http-serve-files:
    build: ./base_http_serve
    image: http_serve
    container_name: serve.local
    volumes:
      - ./base_http_serve/folder:/serve/
    ports:
      - 9000:8000
    networks:
      - network
  mimoto-service.localhost:
    container_name: 'Mimoto-Service'
    image: mosipid/mimoto:0.15.2
    user: root
    ports:
      - '8099:8099'
    environment:
      - container_user=mosip
      - active_profile_env=default
      - SPRING_CONFIG_NAME=mimoto
      - SPRING_CONFIG_LOCATION=/home/mosip/
    networks:
      - network
    volumes:
      - ./config/mimoto-default.properties:/home/mosip/mimoto-default.properties
      - ./config/mimoto-issuers-config.json:/home/mosip/mimoto-issuers-config.json
      - ./config/mimoto-trusted-verifiers.json:/home/mosip/mimoto-trusted-verifiers.json
      - ./certs/oidckeystore.p12:/home/mosip/certs/oidckeystore.p12
    depends_on:
      - http-serve-files

  inji-web.localhost:
    container_name: 'inji-web'
    image: mosipid/inji-web:0.11.0
    ports:
      - '3001:3004'
    environment:
      - DEFAULT_LANG=en
      - MIMOTO_HOST=http://inji-web.localhost:3001/v1/mimoto
    volumes:
      - ./config/mimoto-default.properties:/home/mosip/mimoto-default.properties
      - ./config/mimoto-issuers-config.json:/home/mosip/mimoto-issuers-config.json
      - ./config/mimoto-trusted-verifiers.json:/home/mosip/mimoto-trusted-verifiers.json
      - ./config/credential-template.html:/home/mosip/credential-template.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mimoto-service.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esignet.rule=Host(`inji-web.localhost`)"
    networks:
      - network

networks:
  network:
    name: network-inji
    external: true

volumes:
  cache:
    driver: local
