version: '3.8'

services:

  minio:
    container_name: 'minio-service'
    image: bitnami/minio:2022.2.7-debian-10-r0
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin      # Access Key
      MINIO_ROOT_PASSWORD: minioadmin  # Secret Key

  datashare:
    container_name: 'datashare-service'
    image: mosipid/data-share-service:1.3.0-beta.2
    ports:
      - "8097:8097"
    environment:
      - active_profile_env=inji-default,standalone
      - SPRING_CONFIG_NAME=data-share
      - SPRING_CONFIG_LOCATION=/home/mosip/
    volumes:
      - ./config/data-share-inji-default.properties:/home/mosip/data-share-inji-default.properties
      - ./config/data-share-standalone.properties:/home/mosip/data-share-standalone.properties
    depends_on:
      - minio
    networks:
      - network

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./mimoto_init.sql:/docker-entrypoint-initdb.d/mimoto_init.sql
    networks:
      - network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - network

  http-serve-files:
    build: ./base_http_serve
    image: http_serve
    container_name: serve.local
    volumes:
      - ./base_http_serve/folder:/serve/
    # ports:
    #   - 9000:8000
    networks:
      - network

  mimoto-service:
    container_name: 'mimoto-service'
    image: 'mosipid/mimoto:0.18.1'
    user: root
    ports:
      - '8099:8099'
    environment:
      - container_user=mosip
      - active_profile_env=default
      - SPRING_CONFIG_NAME=mimoto
      - SPRING_CONFIG_LOCATION=/home/mosip/
      - oidc_p12_password=xy4gh6swa2i
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/inji_mimoto # Add Postgres
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - GOOGLE_OAUTH_CLIENT_ID=clientId
      - GOOGLE_OAUTH_CLIENT_SECRET=clientSecret
    volumes:
      - ./config/mimoto-default.properties:/home/mosip/mimoto-default.properties
      - ./certs/oidckeystore.p12:/home/mosip/certs/oidckeystore.p12

      - ./ZscalerRootCertificate-2048-SHA256.crt:/etc/ssl/certs/zscaler.crt:ro
    entrypoint: /bin/sh -c "update-ca-certificates"      

    depends_on:
      - datashare
      - postgres
      - redis
      - http-serve-files
    networks:
      - network

  inji-web.localhost:
    container_name: 'inji-web'
    image: 'mosipid/inji-web:0.13.1'
    ports:
      - '3004:3004'
    environment:
      - DEFAULT_LANG=en
      - MIMOTO_URL=http://inji-web.localhost:3004/v1/mimoto
    volumes:
      - ./config/mimoto-issuers-config.json:/home/mosip/mimoto-issuers-config.json
      - ./config/mimoto-trusted-verifiers.json:/home/mosip/mimoto-trusted-verifiers.json
      - ./config/credential-template.html:/home/mosip/credential-template.html
    depends_on:
      - mimoto-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esignet.rule=Host(`inji-web.localhost`)"
    networks:
      - network

volumes:
  postgres-data:
  redis-data:
  cache:
    driver: local

networks:
  network:
    name: mosip_network
    external: true  